### ISSUE TITLE
Type 'UIApplication' does not conform to protocol 'TikTokURLOpener' (Xcode 16 beta 3)

### ISSUE THREAD

**Issue by Frizlab** [tiktok/tiktok-opensdk-ios#40]
The package does not compile on Xcode 16 beta 3 (and 4).

The `UIApplication` class is made to conform to `TikTokURLOpener` in the package (which is an excessively bad practice, mainly due to the error we get now).

It used to work because `UIApplication` implemented the function `open(_ url: URL, options: [UIApplication.OpenExternalURLOptionsKey : Any], completionHandler completion: ((Bool) -> Void)?)`. Now the function’s signature has changed slightly; it is `open(_ url: URL, options: [UIApplication.OpenExternalURLOptionsKey : Any], completionHandler completion: (@Sendable @MainActor (Bool) -> Void)?)` so it does not work anymore.

Please don’t make external types conform to internal protocols, it is never a good idea.

**Comment by AustinConlon** [comment]
Reproducible on Xcode 16 beta 4 as well.

**Comment by Frizlab** [comment]
@AustinConlon Oh yeah it’s not going away. TikTok must fix their SDK. It’s not complicated but must be done.

**Comment by wendyliga** [comment]
this PR should fix the issue https://github.com/tiktok/tiktok-opensdk-ios/pull/41

**Comment by Kharauzov** [comment]
This issue is still actual for anyone who wants to run his project on Xcode 16 Beta. 
Are there any updates to resolve this blocker?

**Comment by adamvnovak** [comment]
Stil an issue for me.

**Comment by AustinConlon** [comment]
Since the Xcode 16 RC is now out, it would be great to see this prioritized.

**Comment by SimpleApp** [comment]
Xcode 16 is now on the app store. Meaning the SDK officially doesn't work anymore ?

**Comment by WineKai** [comment]
When will this be fixed？

**Comment by andrzli** [comment]
Having the same issue

**Comment by Frizlab** [comment]
Version 2.5 fixes the issue guys…

**Comment by tetkosimi** [comment]
It seems that version 2.5.0 has not been published or at least not available in CocoaPods.
https://github.com/CocoaPods/Specs/tree/master/Specs/a/e/4/TikTokOpenSDKCore
https://github.com/CocoaPods/Specs/tree/master/Specs/b/3/5/TikTokOpenAuthSDK

**Comment by Frizlab** [comment]
It is published and it works via SPM https://github.com/tiktok/tiktok-opensdk-ios/releases/tag/v2.5.0
I don’t know about cocoa pods (but I don’t use it).

**Comment by JW-chenjingwei** [comment]
SPM only suport swift,but not suport cocoapods,please publish whith cocoapods,thanks

**Comment by Frizlab** [comment]
I ain’t the maintainer. My original issue was fixed; you should open a new one if you need it.

**Comment by JW-chenjingwei** [comment]
你好，来信已收到，谢谢
